# You can use this:
deploy:
  type: git
  repo: <repository url>
  branch: [branch]
  token: ''
  message: [message]
  name: [git user]
  email: [git email]
  extend_dirs: [extend directory]
  ignore_hidden: false # default is true
  ignore_pattern: regexp  # whatever file that matches the regexp will be ignored when deploying

# or this:
deploy:
  type: git
  message: [message]
  repo: <repository url>[,branch]
  extend_dirs:
    - [extend directory]
    - [another extend directory]
  ignore_hidden:
    public: false
    [extend directory]: true
    [another extend directory]: false
  ignore_pattern:
    [folder]: regexp  # or you could specify the ignore_pattern under a certain directory

# Multiple repositories
deploy:
  repo:
    # Either syntax is supported
    [repo_name]: <repository url>[,branch]
    [repo_name]:
      url: <repository url>
      branch: [branch]
      deploy:
  repo:
    # Either syntax is supported
    github: https://github.com/user/project.git,branch
    gitee:
      url: https://gitee.com/user/project.git
      branch: branch_name
       # _config.yaml
deploy:
  - type: git
    repo: git@github.com:mj5219054.github.io.git
    branch: master
  - type: git
    repo: git@github.com:mj5219054.github.io.git
    branch: src
    extend_dirs: /
    ignore_hidden: false
    ignore_pattern:
        public: .
      lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    disable : true

      
      
      
      category_dir: categories   # 确认站点配置文件打开
      categories: /categories    #  主题配置文件
      

